# Generated by Django 3.0.7 on 2020-06-11 23:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0002_post2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static\\images\\posts'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static\\images\\posts'),
        ),
    ]
